//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalKnockoutJS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public string Console { get; set; }
    }

    public class GameRepository
    {
        public static IEnumerable<Game> GetGames()
        {
            var gameDB = new myGamesDBEntities();
            var query = from games in gameDB.Games
                        select games;

            return query.ToList();
        }

        public static void InsertGame(Game game)
        {
            var gameDB = new myGamesDBEntities();
            if (game.Name != null)
            {
                gameDB.Games.Add(game);
                gameDB.SaveChanges();
            }

        }
    }
}
